### ISSUE TITLE
Update README (Suggestion)

### ISSUE THREAD

**Issue by manoger** [Unicon/tool13demo#2]
Please, add Gradle equivalent Maven commands too.
I'm using this package manager, and I don't know if it has some compatibility problem.

**Comment by ddelblanco** [comment]
Hi Germano!

I use maven for this project (and most of my projects) so I don't use Gradle, but of course, it is possible to have a Gradle configuration on it at the same time. As far as I know, it is perfectly valid to have both. The only problem I see having both is that I will need to maintain both for any new change, and as said, I don't work with Gradle at this moment.

Anyway. feel free to make a PR with the Gradle configuration and I will add it to the project and I will try to keep it updated if I modify the project.
