### ISSUE TITLE
Config page is asking for the login

### ISSUE THREAD

**Issue by devil1329** [Unicon/tool13demo#45]
I run this repo and try to test the config end point but it is asking for the login credentials. What are those, please tell me. I'm new to this authentication and all and is reading about lti. I figured out most of the part but didn't get anything regarding the login credentials.

![config page](https://github.com/Unicon/tool13demo/assets/68421295/e4979184-cb2f-4200-b8f3-9f97f5bdc385)

**Comment by ddelblanco** [comment]
in this file

https://github.com/Unicon/tool13demo/blob/master/src/main/resources/application.properties

in this section:

##if the password is not set, a random one is generated and displayed on
start in the log.
terracotta.admin.user = admin
#terracotta.admin.password = setyourpassowrdfortheadminuser

You can set the user and password or allow the app to generate a random one
and look at the log for it during the start time.

Regards!

**Comment by devil1329** [comment]
I tried after setting a password, still not working. Also, I tried without setting the password and it was generating a random password, don't know why. Actually, I was trying without a custom password and looked the whole spring terminal for the random password but didn't get any success in that.


![image](https://github.com/Unicon/tool13demo/assets/68421295/5aa4659f-28be-498e-8a0a-f81b19b4c3a8)

**Comment by devil1329** [comment]
Thank You it did helped me.
